version: '3.1'
services:
  app:
    image: 'blog-api-docker.jar'
    ports:
      - "5050:5050"
    depends_on:
      - MYSQL
    networks:
      - blocknet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3305/testProj
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  MYSQL:
    image: mysql
    networks:
      - blocknet
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - TZ=UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  blocknet:
    driver: bridge