version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=testProj
    ports:
      - "3307:3306"
    restart: always
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/testProj?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: always
    depends_on:
      - mysql-standalone


